# Parameters
look_back: 10 # day(s)
target_day: 1 # day(s)
num_epochs: 100
batch_size: 64
test_size: 0.15
random_seed: 42
file_path: data/interim/emissionsWithoutHeader.csv # emissions
model:
  hidden_sizes: [128, 64, 32] # Adjust the number and size of hidden layers
  dropout_rate: 0.1

optimizer:
  learning_rate: 0.001

# Output directory
hydra:
  run:
    dir: outputs/MLP/${now:%Y-%m-%d_%H-%M-%S}
